/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Registration = IDL.Record({
  'paymentScreenshot' : IDL.Text,
  'referral' : IDL.Text,
  'courseLevel' : IDL.Text,
  'whatsapp' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Text,
  'college' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRegistrations' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Registration))],
      [],
    ),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'register' : IDL.Func([Registration], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Registration = IDL.Record({
    'paymentScreenshot' : IDL.Text,
    'referral' : IDL.Text,
    'courseLevel' : IDL.Text,
    'whatsapp' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Text,
    'college' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Registration))],
        [],
      ),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'register' : IDL.Func([Registration], [], []),
  });
};

export const init = ({ IDL }) => { return []; };